### ISSUE TITLE
Consider moving rules not related to software jargon to another packages or another package

### ISSUE THREAD

**Issue by ccoVeille** [jargonLint/jargonLint#11]
Idealy  Jargon could help to detect more things than invalid case/wording

But it could also detect things such as:
- improper English people usage, like "more easy" and co
- an invalid date such as 2024-06-31

It's open for debate, thanks @alexvonme for raising to my attention

**Comment by alexvonme** [comment]
I think the ideal scenario for a project like jargon would be to add rules that everyone adopts similarly, such as heading capitalization (the near-universal consensus seems to be sentence case) while avoiding organization specific rules such those pertaining to contractions.

(I don't mean to invite a discussion on my examples, just trying to illustrate the issue)

**Comment by ccoVeille** [comment]
Does it mean you consider typos like "more easy" or invalid dates would lead to contraction

**Comment by alexvonme** [comment]
No, in this case, I was talking about something as basic as "don't". Some style guides approve or even suggest their use, whereas others like the SUSE one we're increasingly familiar with discourage or outright don't allow them.

This repository could have a contractions file as well, but it would have to be an optional subfolder or something like that since there is now to please everyone with a single file. Maybe the subfolder could have both versions?

In any case, I meant to argue that prioritizing rules that everyone follows, and in many cases needless rewrites, might be a more practical approach.

**Comment by ccoVeille** [comment]
OK, so an extra package could be the solution. It's what I planned to do.

**Comment by ccoVeille** [comment]
The only issue I see is that it could lead to have a lot of packages, with few rules. Instead of rules that could be disabled in each package. Which the norm right now

**Comment by alexvonme** [comment]
For now, we can close this one, since anything generalizable or not directly tech related can be added to ``vale/styles/optional`` after #46.

**Comment by ccoVeille** [comment]
optional in vale styles folder?

I didn't understand it was a vale package.

If so, it has to be named in a way that won't conflict with other packages.

So I would recommend a jargon prefix/suffix

Something like:
- jargonOther
- extraJargon
- jargonExtra

I like the last one, but maybe you would have a better idea
