### ISSUE TITLE
Add content from cspell software terms

### ISSUE THREAD

**Issue by ccoVeille** [jargonLint/jargonLint#6]
https://github.com/streetsidesoftware/cspell-dicts/tree/main/dictionaries%2Fsoftware-terms%2Fdict

**Comment by ccoVeille** [comment]
Related discussion
 https://github.com/streetsidesoftware/cspell-dicts/pull/3310#discussion_r1649606519

**Comment by alexvonme** [comment]
I'm not completely certain about this one, since different organizations can have very different preferences with software.

Perhaps a middle ground might be better. As in, cspell software terms are adopted but are checked with an external organization whose convention we largely follow for any intersections?

**Comment by ccoVeille** [comment]
Let's talk about this one today when we will chat.

**Comment by alexvonme** [comment]
Moved to #31
