### ISSUE TITLE
Interesting logic to add words to valid

### ISSUE THREAD

**Issue by ccoVeille** [jargonLint/jargonLint#62]
This rule is using filterto add words

https://github.com/redhat-documentation/vale-at-red-hat/blob/main/.vale%2Fstyles%2FRedHat%2FSpelling.yml

I think it difdersfrom adding a words to vocabulary (Vocab.txt) as it avoid that vale would suggest them (to be checked)

**Comment by alexvonme** [comment]
Filter isn't useful in our case since they can only be used with Vale rules that extend [spelling](https://vale.sh/docs/topics/styles/#spelling). 

Vale explains filters and ignorefiles in ["Ignoring non-dictionary words"](https://vale.sh/docs/topics/styles/#ignoring-non-dictionary-words), below the spelling extension:
- Filters are added to rules as case-sensitive regex exceptions to spelling rules
- Ignorefiles are plain-text files where the first letter of each word is not case-sensitive.

Then comes in [Vocabulary](https://vale.sh/docs/topics/vocab/#case-sensitivity) which is far more customizable since they can be case-sensitive or not. This depends on whether the style guide author uses Vale.terms, as explained below the title ["Case sensitivity"](https://vale.sh/docs/topics/vocab/#case-sensitivity) within the same page.

Vale generally seems to suggest ignore files and vocabularies for long term solutions in ["Relation to ignore files"](https://vale.sh/docs/topics/vocab/#relation-to-ignore-files) by stating that **"ignore files are for style creators while vocabularies are for style users"**. This seems sensible since organizing and maintaining filters within the rules requires much more effort and those filters would only apply within the context of that specific rule.

As such, I suggest closing this issue as filter functionality is limited and easily replaced by ignorefiles or the Vocabulary functionality.
